insert into t_club(club_name,full_name,location,owner,chairman,coach) values ('OSK','ACS Sepsi OSK Sepsiszentgyörgy','Sfântu Gheorghe','Diószegi László','Hadnagy Attila','Cristiano Bergodi')
insert into t_club(club_name,full_name,location,owner,chairman,coach) values ('Dinamo','Fotbal Club Dinamo București','București','Dorin Șerdean','Constantin Eftimescu','Dušan Uhrin Jr.')
insert into t_club(club_name,full_name,location,owner,chairman,coach) values ('FCSB','SC Fotbal Club FCSB SA','București','George Becali','Valeriu Argăseală','Anton Petrea')
insert into t_club(club_name,full_name,location,owner,chairman,coach) values ('CFR','SC Fotbal Club CFR 1907 Cluj SA','Cluj','Ioan Varga','Cristian Balaj','Dan Petrescu')
insert into t_player(firstname, lastname, age, salary, goals, position, place_of_birth, id_club) values ('Chipciu','Alexandru Mihăiță',32,3000,452,'Winger, attacking midfielder','Brăila, Romania',4)
insert into t_player(firstname, lastname, age, salary, goals, position, place_of_birth, id_club) values ('Fülöp','István Sándor',31,3000,214,'Winger, attacking midfielder','Târgu Mureș, Romania',1)
insert into t_player(firstname, lastname, age, salary, goals, position, place_of_birth, id_club) values ('Nedelcu','Dragoș Ionuț ',25,3000,168,'Defensive midfielder, centre-back','Constanța, Romania',3)
insert into t_player(firstname, lastname, age, salary, goals, position, place_of_birth, id_club) values ('Filip','Steliano ',27,3000,238,'Left full back','Buzău, Romania',2)
insert into t_player(firstname, lastname, age, salary, goals, position, place_of_birth, id_club) values ('Fofana','Boubacar ',32,3000,309,'Defensive midfielder','Conakry, Guinea',1)
insert into t_player(firstname, lastname, age, salary, goals, position, place_of_birth, id_club) values ('Burcă','Andrei Andonie',28,3000,383,'	Defender','Bacău, Romania',4)
insert into t_player(firstname, lastname, age, salary, goals, position, place_of_birth, id_club) values ('Sorescu','Deian Cristian',24,3000,196,'Winger, right-back','Moldova Nouă, Romania',2)
insert into t_player(firstname, lastname, age, salary, goals, position, place_of_birth, id_club) values ('Pintilii','Doru Mihai',37,3000,397,'Midfielder','Iași, Romania',3)
insert into t_user(username, password, email) values ('username', 'password','abc@def.com')
insert into t_user(username, password, email) values ('username1', 'password','abc@def.com')

